#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUTPUT="${1:-$ROOT/dist/ffmpeg-btbn-corresponding-source.tar.xz}"
BTBN_TAG="autobuild-2026-06-30-13-34"
BTBN_COMMIT="7a83528ea3431e9eca982a712bc3a7cd0789d5d0"
FFMPEG_COMMIT="7d0e8420048cffd0ca3883b877ead2390496d0b2"
TARGET="win64"
LINUX_TARGETS=(linux64 linuxarm64)
VARIANT="gpl"
ADDINS="7.1"
SOURCE_DATE_EPOCH="1782826542"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

for command in git node; do
  command -v "$command" >/dev/null || { echo "$command is required" >&2; exit 1; }
done

if [[ "${1:-}" == "--check-recipe" ]]; then
  [[ "$(git ls-remote https://github.com/BtbN/FFmpeg-Builds.git "refs/tags/$BTBN_TAG" | awk '{print $1}')" == "$BTBN_COMMIT" ]]
  git -C "$WORK" init --quiet ffmpeg-check
  git -C "$WORK/ffmpeg-check" fetch --quiet --depth=1 https://github.com/FFmpeg/FFmpeg.git "$FFMPEG_COMMIT"
  [[ "$(git -C "$WORK/ffmpeg-check" rev-parse FETCH_HEAD)" == "$FFMPEG_COMMIT" ]]
  echo "Verified BtbN $BTBN_TAG at $BTBN_COMMIT and FFmpeg $FFMPEG_COMMIT"
  exit 0
fi

for command in docker tar xz; do
  command -v "$command" >/dev/null || { echo "$command is required" >&2; exit 1; }
done
docker info >/dev/null

mkdir -p "$(dirname "$OUTPUT")" "$WORK/bundle/vrrelay-ffmpeg-source/dependency-sources"
git clone --quiet https://github.com/BtbN/FFmpeg-Builds.git "$WORK/FFmpeg-Builds"
git -C "$WORK/FFmpeg-Builds" checkout --quiet --detach "$BTBN_COMMIT"
[[ "$(git -C "$WORK/FFmpeg-Builds" rev-parse "refs/tags/$BTBN_TAG^{commit}")" == "$BTBN_COMMIT" ]]

# Upstream's downloader captures the complete dependency source set referenced
# by this pinned recipe. It intentionally downloads more than the GPL variant
# needs rather than risking omission of a statically linked component.
(cd "$WORK/FFmpeg-Builds" && ./download.sh)

git clone --quiet --filter=blob:none https://github.com/FFmpeg/FFmpeg.git "$WORK/FFmpeg"
git -C "$WORK/FFmpeg" checkout --quiet --detach "$FFMPEG_COMMIT"
git -C "$WORK/FFmpeg" archive --format=tar --prefix=ffmpeg-exact/ "$FFMPEG_COMMIT" | xz -9e > "$WORK/FFmpeg-Builds/.cache/downloads/ffmpeg-exact-$FFMPEG_COMMIT.tar.xz"

rm -rf "$WORK/FFmpeg-Builds/.git"
mv "$WORK/FFmpeg-Builds" "$WORK/bundle/vrrelay-ffmpeg-source/build-recipe"
mv "$WORK/bundle/vrrelay-ffmpeg-source/build-recipe/.cache/downloads/"* "$WORK/bundle/vrrelay-ffmpeg-source/dependency-sources/"
rm -rf "$WORK/bundle/vrrelay-ffmpeg-source/build-recipe/.cache"

cat > "$WORK/bundle/vrrelay-ffmpeg-source/REBUILD.md" <<EOF
# Rebuilding the bundled FFmpeg binaries

This source bundle corresponds to the VRRelay runtime binary recorded as:

- BtbN release: \`$BTBN_TAG\`
- BtbN recipe commit: \`$BTBN_COMMIT\`
- FFmpeg commit: \`$FFMPEG_COMMIT\`
- Windows x64: \`./makeimage.sh $TARGET $VARIANT $ADDINS\`, then \`./build.sh $TARGET $VARIANT $ADDINS\`
- Linux x64: \`./makeimage.sh ${LINUX_TARGETS[0]} $VARIANT $ADDINS\`, then \`./build.sh ${LINUX_TARGETS[0]} $VARIANT $ADDINS\`
- Linux arm64: \`./makeimage.sh ${LINUX_TARGETS[1]} $VARIANT $ADDINS\`, then \`./build.sh ${LINUX_TARGETS[1]} $VARIANT $ADDINS\`

The \`dependency-sources\` directory contains the source snapshots downloaded by the pinned recipe plus \`ffmpeg-exact-$FFMPEG_COMMIT.tar.xz\`. The \`build-recipe\` directory contains the upstream scripts and patches. Extract the exact FFmpeg archive into a local Git repository and expose that commit through a local branch, then set \`FFMPEG_REPO_OVERRIDE\` to that repository and \`GIT_BRANCH_OVERRIDE\` to that branch before running the build command. This prevents the upstream release branch from advancing during a rebuild.

Use the container toolchain generated by the pinned \`makeimage.sh\` invocation. The resulting archive name and executable version must match \`deploy/runtime-manifest.json\` in the VRRelay source tree; compare the produced binary behavior and configuration with the release provenance before distribution.
EOF

export SOURCE_DATE_EPOCH
node "$ROOT/script/windows-source-bundle.mjs" --create \
  "$WORK/bundle/vrrelay-ffmpeg-source" \
  "$WORK/bundle/vrrelay-ffmpeg-source/SOURCE-BUNDLE.json"

docker run --rm \
  -e SOURCE_DATE_EPOCH \
  -v "$WORK/bundle:/source:ro" \
  -v "$(dirname "$OUTPUT"):/output" \
  debian:bookworm-slim \
  sh -ec 'apt-get update >/dev/null && apt-get install -y --no-install-recommends xz-utils >/dev/null && tar --sort=name --mtime="@$SOURCE_DATE_EPOCH" --owner=0 --group=0 --numeric-owner -C /source -cJf "/output/'"$(basename "$OUTPUT")"'" vrrelay-ffmpeg-source'

node "$ROOT/script/windows-source-bundle.mjs" --verify "$OUTPUT"
shasum -a 256 "$OUTPUT"
